version: '3'

services:
  app:
    build:
      context: .
      dockerfile: deploy/docker/Dockerfile
    image: plataurus-web
    restart: always
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=9010
    ports:
      - 9010:9010
    container_name: plataurus-web
